name: Deployment

on:
  push:
    branches:
      - deploy

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy
        # echo deploy to the shell
        run: echo deploy
