name: Scorecards dependency analysis

on:
  pull_request:

jobs:
  dependency-analysis:
    name: Scorecards dependency analysis
    runs-on: ubuntu-latest
    env:
      GITHUB_PR_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Run analysis
        run: |
          docker run --rm \
          -e GITHUB_PR_NUMBER=$GITHUB_PR_NUMBER \
          -e GITHUB_TOKEN=$GITHUB_TOKEN \
          ghcr.io/naveensrinivasan/scorecard-action-dependency-analysis:naveen-feat-dependency-analysis
