name: Scorecards dependency analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: write

jobs:
  dependency-analysis:
    name: Scorecards dependency analysis
    runs-on: ubuntu-latest
    env:
      GITHUB_PR_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}


    steps:
      - name: Checkout code
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
        with:
          persist-credentials: false
      - name: Print environment variables
        run: |
          echo "GITHUB_PR_NUMBER: $GITHUB_PR_NUMBER"
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY_OWNER
          echo $GITHUB_ACTOR
        shell: bash

      - name: Run analysis
        run: |
          docker run --rm \
          -e GITHUB_PR_NUMBER=$GITHUB_PR_NUMBER \
          -e GITHUB_TOKEN=$GITHUB_TOKEN \
          -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
          -e GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER \
          -e GITHUB_SHA=$GITHUB_SHA \
          -e GITHUB_ACTOR=$GITHUB_ACTOR \
          ghcr.io/naveensrinivasan/scorecard-action-dependency-analysis:latest
